/*
Carbide REST API

Testing InstanceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_InstanceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InstanceAPIService BatchCreateInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.InstanceAPI.BatchCreateInstance(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceAPIService CreateInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.InstanceAPI.CreateInstance(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceAPIService DeleteInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var instanceId string

		httpRes, err := apiClient.InstanceAPI.DeleteInstance(context.Background(), org, instanceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceAPIService GetAllInfinibandInterface", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var instanceId string

		resp, httpRes, err := apiClient.InstanceAPI.GetAllInfinibandInterface(context.Background(), org, instanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceAPIService GetAllInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.InstanceAPI.GetAllInstance(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceAPIService GetAllInterface", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var instanceId string

		resp, httpRes, err := apiClient.InstanceAPI.GetAllInterface(context.Background(), org, instanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceAPIService GetInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var instanceId string

		resp, httpRes, err := apiClient.InstanceAPI.GetInstance(context.Background(), org, instanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceAPIService GetInstanceStatusHistory", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var instanceId string

		resp, httpRes, err := apiClient.InstanceAPI.GetInstanceStatusHistory(context.Background(), org, instanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceAPIService UpdateInstance", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var instanceId string

		resp, httpRes, err := apiClient.InstanceAPI.UpdateInstance(context.Background(), org, instanceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
