/*
Carbide REST API

Testing NetworkSecurityGroupAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_NetworkSecurityGroupAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test NetworkSecurityGroupAPIService CreateNetworkSecurityGroup", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.NetworkSecurityGroupAPI.CreateNetworkSecurityGroup(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NetworkSecurityGroupAPIService DeleteNetworkSecurityGroup", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var networkSecurityGroupId string

		httpRes, err := apiClient.NetworkSecurityGroupAPI.DeleteNetworkSecurityGroup(context.Background(), org, networkSecurityGroupId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NetworkSecurityGroupAPIService GetAllNetworkSecurityGroup", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.NetworkSecurityGroupAPI.GetAllNetworkSecurityGroup(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NetworkSecurityGroupAPIService GetNetworkSecurityGroup", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var networkSecurityGroupId string

		resp, httpRes, err := apiClient.NetworkSecurityGroupAPI.GetNetworkSecurityGroup(context.Background(), org, networkSecurityGroupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NetworkSecurityGroupAPIService UpdateNetworkSecurityGroup", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var networkSecurityGroupId string

		resp, httpRes, err := apiClient.NetworkSecurityGroupAPI.UpdateNetworkSecurityGroup(context.Background(), org, networkSecurityGroupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
