/*
Carbide REST API

Testing OperatingSystemAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_OperatingSystemAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OperatingSystemAPIService CreateOperatingSystem", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.OperatingSystemAPI.CreateOperatingSystem(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperatingSystemAPIService DeleteOperatingSystem", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var operatingSystemId string

		httpRes, err := apiClient.OperatingSystemAPI.DeleteOperatingSystem(context.Background(), org, operatingSystemId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperatingSystemAPIService GetAllOperatingSystem", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.OperatingSystemAPI.GetAllOperatingSystem(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperatingSystemAPIService GetOperatingSystem", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var operatingSystemId string

		resp, httpRes, err := apiClient.OperatingSystemAPI.GetOperatingSystem(context.Background(), org, operatingSystemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperatingSystemAPIService UpdateOperatingSystem", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var operatingSystemId string

		resp, httpRes, err := apiClient.OperatingSystemAPI.UpdateOperatingSystem(context.Background(), org, operatingSystemId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
