/*
Carbide REST API

Testing SSHKeyGroupAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_SSHKeyGroupAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SSHKeyGroupAPIService CreateSshKeyGroup", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.SSHKeyGroupAPI.CreateSshKeyGroup(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SSHKeyGroupAPIService DeleteSshKeyGroup", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var sshKeyGroupId string

		httpRes, err := apiClient.SSHKeyGroupAPI.DeleteSshKeyGroup(context.Background(), org, sshKeyGroupId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SSHKeyGroupAPIService GetAllSshKeyGroup", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.SSHKeyGroupAPI.GetAllSshKeyGroup(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SSHKeyGroupAPIService GetSshKeyGroup", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var sshKeyGroupId string

		resp, httpRes, err := apiClient.SSHKeyGroupAPI.GetSshKeyGroup(context.Background(), org, sshKeyGroupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SSHKeyGroupAPIService UpdateSshKeyGroup", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var sshKeyGroupId string

		resp, httpRes, err := apiClient.SSHKeyGroupAPI.UpdateSshKeyGroup(context.Background(), org, sshKeyGroupId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
