/*
Carbide REST API

Testing ExpectedMachineAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_ExpectedMachineAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ExpectedMachineAPIService BatchCreateExpectedMachines", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.ExpectedMachineAPI.BatchCreateExpectedMachines(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExpectedMachineAPIService BatchUpdateExpectedMachines", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.ExpectedMachineAPI.BatchUpdateExpectedMachines(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExpectedMachineAPIService CreateExpectedMachine", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.ExpectedMachineAPI.CreateExpectedMachine(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExpectedMachineAPIService DeleteExpectedMachine", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var expectedMachineId string

		httpRes, err := apiClient.ExpectedMachineAPI.DeleteExpectedMachine(context.Background(), org, expectedMachineId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExpectedMachineAPIService GetAllExpectedMachine", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.ExpectedMachineAPI.GetAllExpectedMachine(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExpectedMachineAPIService GetExpectedMachine", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var expectedMachineId string

		resp, httpRes, err := apiClient.ExpectedMachineAPI.GetExpectedMachine(context.Background(), org, expectedMachineId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ExpectedMachineAPIService UpdateExpectedMachine", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var expectedMachineId string

		resp, httpRes, err := apiClient.ExpectedMachineAPI.UpdateExpectedMachine(context.Background(), org, expectedMachineId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
