/*
Carbide REST API

Testing NVLinkLogicalPartitionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_NVLinkLogicalPartitionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test NVLinkLogicalPartitionAPIService CreateNvlinkLogicalPartition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.NVLinkLogicalPartitionAPI.CreateNvlinkLogicalPartition(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NVLinkLogicalPartitionAPIService DeleteNvlinkLogicalPartition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var nvLinkLogicalPartitionId string

		httpRes, err := apiClient.NVLinkLogicalPartitionAPI.DeleteNvlinkLogicalPartition(context.Background(), org, nvLinkLogicalPartitionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NVLinkLogicalPartitionAPIService GetAllNvlinkInterface", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.NVLinkLogicalPartitionAPI.GetAllNvlinkInterface(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NVLinkLogicalPartitionAPIService GetAllNvlinkLogicalPartition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.NVLinkLogicalPartitionAPI.GetAllNvlinkLogicalPartition(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NVLinkLogicalPartitionAPIService GetNvlinkLogicalPartition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var nvLinkLogicalPartitionId string

		resp, httpRes, err := apiClient.NVLinkLogicalPartitionAPI.GetNvlinkLogicalPartition(context.Background(), org, nvLinkLogicalPartitionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test NVLinkLogicalPartitionAPIService UpdateNvlinkLogicalPartition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var nvLinkLogicalPartitionId string

		resp, httpRes, err := apiClient.NVLinkLogicalPartitionAPI.UpdateNvlinkLogicalPartition(context.Background(), org, nvLinkLogicalPartitionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
