/*
Carbide REST API

Testing MachineAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_MachineAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MachineAPIService DeleteMachine", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var machineId string

		httpRes, err := apiClient.MachineAPI.DeleteMachine(context.Background(), org, machineId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MachineAPIService GetAllMachine", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.MachineAPI.GetAllMachine(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MachineAPIService GetAllMachineCapabilities", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.MachineAPI.GetAllMachineCapabilities(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MachineAPIService GetMachine", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var machineId string

		resp, httpRes, err := apiClient.MachineAPI.GetMachine(context.Background(), org, machineId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MachineAPIService GetMachineStatusHistory", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var machineId string

		resp, httpRes, err := apiClient.MachineAPI.GetMachineStatusHistory(context.Background(), org, machineId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MachineAPIService UpdateMachine", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var machineId string

		resp, httpRes, err := apiClient.MachineAPI.UpdateMachine(context.Background(), org, machineId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
