/*
Carbide REST API

Testing SSHKeyAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_SSHKeyAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SSHKeyAPIService CreateSshKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.SSHKeyAPI.CreateSshKey(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SSHKeyAPIService DeleteSshKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var sshKeyId string

		httpRes, err := apiClient.SSHKeyAPI.DeleteSshKey(context.Background(), org, sshKeyId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SSHKeyAPIService GetAllSshKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.SSHKeyAPI.GetAllSshKey(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SSHKeyAPIService GetSshKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var sshKeyId string

		resp, httpRes, err := apiClient.SSHKeyAPI.GetSshKey(context.Background(), org, sshKeyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SSHKeyAPIService UpdateSshKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var sshKeyId string

		resp, httpRes, err := apiClient.SSHKeyAPI.UpdateSshKey(context.Background(), org, sshKeyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
