/*
Carbide REST API

Testing SiteAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_SiteAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SiteAPIService CreateSite", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.SiteAPI.CreateSite(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SiteAPIService DeleteSite", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var siteId string

		httpRes, err := apiClient.SiteAPI.DeleteSite(context.Background(), org, siteId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SiteAPIService GetAllSite", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.SiteAPI.GetAllSite(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SiteAPIService GetSite", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var siteId string

		resp, httpRes, err := apiClient.SiteAPI.GetSite(context.Background(), org, siteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SiteAPIService GetSiteStatusHistory", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var siteId string

		resp, httpRes, err := apiClient.SiteAPI.GetSiteStatusHistory(context.Background(), org, siteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SiteAPIService UpdateSite", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var siteId string

		resp, httpRes, err := apiClient.SiteAPI.UpdateSite(context.Background(), org, siteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
