/*
Carbide REST API

Testing VPCAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_VPCAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VPCAPIService CreateVpc", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.VPCAPI.CreateVpc(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VPCAPIService DeleteVpc", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var vpcId string

		httpRes, err := apiClient.VPCAPI.DeleteVpc(context.Background(), org, vpcId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VPCAPIService GetAllVpc", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.VPCAPI.GetAllVpc(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VPCAPIService GetVpc", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var vpcId string

		resp, httpRes, err := apiClient.VPCAPI.GetVpc(context.Background(), org, vpcId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VPCAPIService UpdateVpc", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var vpcId string

		resp, httpRes, err := apiClient.VPCAPI.UpdateVpc(context.Background(), org, vpcId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VPCAPIService UpdateVpcVirtualization", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var vpcId string

		resp, httpRes, err := apiClient.VPCAPI.UpdateVpcVirtualization(context.Background(), org, vpcId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
