/*
Carbide REST API

Testing InstanceTypeAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_InstanceTypeAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InstanceTypeAPIService CreateInstanceType", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.InstanceTypeAPI.CreateInstanceType(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceTypeAPIService CreateInstanceTypeMachineAssociation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var instanceTypeId string

		resp, httpRes, err := apiClient.InstanceTypeAPI.CreateInstanceTypeMachineAssociation(context.Background(), org, instanceTypeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceTypeAPIService DeleteInstanceType", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var instanceTypeId string

		httpRes, err := apiClient.InstanceTypeAPI.DeleteInstanceType(context.Background(), org, instanceTypeId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceTypeAPIService DeleteInstanceTypeMachineAssociation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var instanceTypeId string
		var machineAssociationId string

		httpRes, err := apiClient.InstanceTypeAPI.DeleteInstanceTypeMachineAssociation(context.Background(), org, instanceTypeId, machineAssociationId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceTypeAPIService GetAllInstanceType", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.InstanceTypeAPI.GetAllInstanceType(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceTypeAPIService GetInstanceType", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var instanceTypeId string

		resp, httpRes, err := apiClient.InstanceTypeAPI.GetInstanceType(context.Background(), org, instanceTypeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceTypeAPIService GetInstanceTypeMachineAssociation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var instanceTypeId string

		resp, httpRes, err := apiClient.InstanceTypeAPI.GetInstanceTypeMachineAssociation(context.Background(), org, instanceTypeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InstanceTypeAPIService UpdateInstanceType", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var instanceTypeId string

		resp, httpRes, err := apiClient.InstanceTypeAPI.UpdateInstanceType(context.Background(), org, instanceTypeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
