/*
Carbide REST API

Testing TenantAccountAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_TenantAccountAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TenantAccountAPIService CreateTenantAccount", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.TenantAccountAPI.CreateTenantAccount(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TenantAccountAPIService DeleteTenantAccount", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var accountId string

		httpRes, err := apiClient.TenantAccountAPI.DeleteTenantAccount(context.Background(), org, accountId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TenantAccountAPIService GetAllTenantAccount", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.TenantAccountAPI.GetAllTenantAccount(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TenantAccountAPIService GetTenantAccount", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var accountId string

		resp, httpRes, err := apiClient.TenantAccountAPI.GetTenantAccount(context.Background(), org, accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TenantAccountAPIService UpdateTenantAccount", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var accountId string

		resp, httpRes, err := apiClient.TenantAccountAPI.UpdateTenantAccount(context.Background(), org, accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
