/*
Carbide REST API

Testing SubnetAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_SubnetAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SubnetAPIService CreateSubnet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.SubnetAPI.CreateSubnet(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubnetAPIService DeleteSubnet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var subnetId string

		httpRes, err := apiClient.SubnetAPI.DeleteSubnet(context.Background(), org, subnetId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubnetAPIService GetAllSubnet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.SubnetAPI.GetAllSubnet(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubnetAPIService GetSubnet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var subnetId string

		resp, httpRes, err := apiClient.SubnetAPI.GetSubnet(context.Background(), org, subnetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubnetAPIService UpdateSubnet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var subnetId string

		resp, httpRes, err := apiClient.SubnetAPI.UpdateSubnet(context.Background(), org, subnetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
