/*
Carbide REST API

Testing IPBlockAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_IPBlockAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IPBlockAPIService CreateIpblock", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.IPBlockAPI.CreateIpblock(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IPBlockAPIService DeleteIpblock", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var ipBlockId string

		httpRes, err := apiClient.IPBlockAPI.DeleteIpblock(context.Background(), org, ipBlockId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IPBlockAPIService GetAllDerivedIpblock", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var ipBlockId string

		resp, httpRes, err := apiClient.IPBlockAPI.GetAllDerivedIpblock(context.Background(), org, ipBlockId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IPBlockAPIService GetAllIpblock", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.IPBlockAPI.GetAllIpblock(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IPBlockAPIService GetIpblock", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var ipBlockId string

		resp, httpRes, err := apiClient.IPBlockAPI.GetIpblock(context.Background(), org, ipBlockId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IPBlockAPIService UpdateIpblock", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var ipBlockId string

		resp, httpRes, err := apiClient.IPBlockAPI.UpdateIpblock(context.Background(), org, ipBlockId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
