/*
Carbide REST API

Testing AllocationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_AllocationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AllocationAPIService CreateAllocation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.AllocationAPI.CreateAllocation(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AllocationAPIService CreateAllocationConstraint", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var allocationId string

		resp, httpRes, err := apiClient.AllocationAPI.CreateAllocationConstraint(context.Background(), org, allocationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AllocationAPIService DeleteAllocation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var allocationId string

		httpRes, err := apiClient.AllocationAPI.DeleteAllocation(context.Background(), org, allocationId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AllocationAPIService DeleteAllocationConstraint", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var allocationId string
		var allocationConstraintId string

		httpRes, err := apiClient.AllocationAPI.DeleteAllocationConstraint(context.Background(), org, allocationId, allocationConstraintId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AllocationAPIService GetAllAllocation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.AllocationAPI.GetAllAllocation(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AllocationAPIService GetAllAllocationConstraint", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var allocationId string

		resp, httpRes, err := apiClient.AllocationAPI.GetAllAllocationConstraint(context.Background(), org, allocationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AllocationAPIService GetAllocation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var allocationId string

		resp, httpRes, err := apiClient.AllocationAPI.GetAllocation(context.Background(), org, allocationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AllocationAPIService GetAllocationConstraint", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var allocationId string
		var allocationConstraintId string

		resp, httpRes, err := apiClient.AllocationAPI.GetAllocationConstraint(context.Background(), org, allocationId, allocationConstraintId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AllocationAPIService UpdateAllocation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var allocationId string

		resp, httpRes, err := apiClient.AllocationAPI.UpdateAllocation(context.Background(), org, allocationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AllocationAPIService UpdateAllocationConstraint", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var allocationId string
		var allocationConstraintId string

		resp, httpRes, err := apiClient.AllocationAPI.UpdateAllocationConstraint(context.Background(), org, allocationId, allocationConstraintId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
