/*
Carbide REST API

Testing DPUExtensionServiceAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_DPUExtensionServiceAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DPUExtensionServiceAPIService CreateDpuExtensionService", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.DPUExtensionServiceAPI.CreateDpuExtensionService(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DPUExtensionServiceAPIService DeleteDpuExtensionService", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var dpuExtensionServiceId string

		httpRes, err := apiClient.DPUExtensionServiceAPI.DeleteDpuExtensionService(context.Background(), org, dpuExtensionServiceId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DPUExtensionServiceAPIService DeleteDpuExtensionServiceVersion", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var dpuExtensionServiceId string
		var version string

		httpRes, err := apiClient.DPUExtensionServiceAPI.DeleteDpuExtensionServiceVersion(context.Background(), org, dpuExtensionServiceId, version).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DPUExtensionServiceAPIService GetAllDpuExtensionService", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.DPUExtensionServiceAPI.GetAllDpuExtensionService(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DPUExtensionServiceAPIService GetDpuExtensionService", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var dpuExtensionServiceId string

		resp, httpRes, err := apiClient.DPUExtensionServiceAPI.GetDpuExtensionService(context.Background(), org, dpuExtensionServiceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DPUExtensionServiceAPIService GetDpuExtensionServiceVersion", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var dpuExtensionServiceId string
		var version string

		resp, httpRes, err := apiClient.DPUExtensionServiceAPI.GetDpuExtensionServiceVersion(context.Background(), org, dpuExtensionServiceId, version).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DPUExtensionServiceAPIService UpdateDpuExtensionService", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var dpuExtensionServiceId string

		resp, httpRes, err := apiClient.DPUExtensionServiceAPI.UpdateDpuExtensionService(context.Background(), org, dpuExtensionServiceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
