/*
Carbide REST API

Testing VPCPrefixAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_VPCPrefixAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VPCPrefixAPIService CreateVpcPrefix", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.VPCPrefixAPI.CreateVpcPrefix(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VPCPrefixAPIService DeleteVpcPrefix", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var vpcPrefixId string

		httpRes, err := apiClient.VPCPrefixAPI.DeleteVpcPrefix(context.Background(), org, vpcPrefixId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VPCPrefixAPIService GetAllVpcPrefix", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.VPCPrefixAPI.GetAllVpcPrefix(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VPCPrefixAPIService GetVpcPrefix", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var vpcPrefixId string

		resp, httpRes, err := apiClient.VPCPrefixAPI.GetVpcPrefix(context.Background(), org, vpcPrefixId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VPCPrefixAPIService UpdateVpcPrefix", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var vpcPrefixId string

		resp, httpRes, err := apiClient.VPCPrefixAPI.UpdateVpcPrefix(context.Background(), org, vpcPrefixId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
