/*
Carbide REST API

Testing InfiniBandPartitionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
	"context"
	openapiclient "github.com/nvidia/bare-metal-manager-rest/client"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_client_InfiniBandPartitionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InfiniBandPartitionAPIService CreateInfinibandPartition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.InfiniBandPartitionAPI.CreateInfinibandPartition(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InfiniBandPartitionAPIService DeleteInfinibandPartition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var infiniBandPartitionId string

		httpRes, err := apiClient.InfiniBandPartitionAPI.DeleteInfinibandPartition(context.Background(), org, infiniBandPartitionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InfiniBandPartitionAPIService GetAllInfinibandPartition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string

		resp, httpRes, err := apiClient.InfiniBandPartitionAPI.GetAllInfinibandPartition(context.Background(), org).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InfiniBandPartitionAPIService GetInfinibandPartition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var infiniBandPartitionId string

		resp, httpRes, err := apiClient.InfiniBandPartitionAPI.GetInfinibandPartition(context.Background(), org, infiniBandPartitionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InfiniBandPartitionAPIService UpdateInfinibandPartition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var org string
		var infiniBandPartitionId string

		resp, httpRes, err := apiClient.InfiniBandPartitionAPI.UpdateInfinibandPartition(context.Background(), org, infiniBandPartitionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
